### PR TITLE
add: Deepesh Patil

### PR DESCRIPTION
**Pull request by deepesh611**
## Checklist

- [x] I have read and followed the [Contribution Guidelines](https://github.com/codeaashu/DevDisplay/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] I have updated the documentation to reflect the changes I've made.
- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
image

### CODE REVIEW

**Comment by codeaashu** [comment]
Hi @LazyCodwr, thanks for your interest in contributing to DevDisplay!

Before we proceed, we noticed you adding your profile on #DevDisplay but forgot to star the repo. It's like making an amazing sandwich and forgetting to take a bite! -- I think our repo's feeling a little lonely without your 🤗 So, be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻

**Comment by codeaashu** [comment]
& one more things 
download
& one more thing you changes 10 file in this 

join our WhatsApp community 
and share the details info of your 10 file changes in this apart from your profile add 
https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4

**Comment by deepesh611** [comment]
> & one more things 
> download
> & one more thing you changes 10 file in this 
> 
> join our WhatsApp community 
> and share the details info of your 10 file changes in this apart from your profile add 
> https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4

My bad, looks like i forgot to mention the folder `.idea` in the `.gitignore`.
It was added because I was using Pycharm 

Lemme fix that..

**Comment by deepesh611** [comment]
Ooh, and one more thing I wanna ask. Do u mind if I add the `Instagram` block as well along the Twitter and LinkedIn block, in `Profile.jsx`

**Comment by deepesh611** [comment]
> > & one more things
> > download
> > & one more thing you changes 10 file in this
> > join our WhatsApp community
> > and share the details info of your 10 file changes in this apart from your profile add
> > https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4
> 
> My bad, looks like i forgot to mention the folder `.idea` in the `.gitignore`. It was added because I was using Pycharm
> 
> Lemme fix that..

I have fixed that issue
image

**Comment by deepesh611** [comment]
> Ooh, and one more thing I wanna ask. Do u mind if I add the `Instagram` block as well along the Twitter and LinkedIn block, in `Profile.jsx`

hey yoo, what abt this ?

**Pull request merged**
