### PR TITLE
The Search Feature of Skills cirteria implement from one skill to mutliple Skills

### PR DESCRIPTION
**Pull request by Sambashivarao-Boyina**
… search and working very well and there is not errors. Also it is adaptable with dark mode

## Description

I have the changed the search feature  when criteria is skill form single skill to multiple skills now use can filter profiles based on multiple skills . if any user matches any single skill in given skills set it will be showed

after we can remove the each skill and clear all the skills 

## Related Issues

This is the Issue, I have raised in issues box  #330
It  is under **gssoc-ext** , **hacktoberfest2024**

## Changes Proposed

Before the the changes it does not able to filter profiles when we enter multiple skills 

Screenshot from 2024-10-19 17-30-41

Now
when a user enters any skill and clicks enter, it will be added to the **searchSkills** list and after that, we can enter multiple skills by entering in the textbox and clicking enter. we can also remove them one by one also

Screenshot from 2024-10-24 15-20-30

Screenshot from 2024-10-24 15-20-41

It also supports dark theme also

Screenshot from 2024-10-24 15-20-50

Is also supported on all screens

## Checklist

- [X] I have read and followed the [Contribution Guidelines](https://github.com/codeaashu/DevDisplay/blob/master/CONTRIBUTING.md).
- [X] All new and existing tests passed.
- [X] I have updated the documentation to reflect the changes I've made.
- [X] My code follows the code style of this project.
- [X] The title of my pull request is a short description of the requested changes.

## Note to reviewers

I have changed the logic in the Homepage I separate the filter logic of criteria of skill with the remaining and write a new logic I have the **shuffledProfiles** for filter data if I clear the skills I set the **shuffledProfiles** 

I have tested the code in all ways it working properly. I didn't see any errors

If my code satisfied your standards and if my code is valid and working properly. please merge the code and also add the badges of **gssoc-ext** ,  **hacktoberfest2024**.

Thank you

### CODE REVIEW

**Comment by Sambashivarao-Boyina** [comment]
Thank You for accepting my code

**Comment by madhukalita** [comment]
Join DevDisplay Whatsapp community
for future update on this and also for upcoming project collabration through DevDisplay Community
https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4

**Comment by madhukalita** [comment]
hayy @Sambashivarao-Boyina 
one task for u 

checkout the latest PR #386

Add voice search functionality in search

**Comment by Sambashivarao-Boyina** [comment]
> hayy @Sambashivarao-Boyina one task for u
> 
> checkout the latest PR #386
> 
> Add voice search functionality in search

Yes, I will do this.

could you assign this to me .

I have raised an issue of this in issues box #432 could you please assign this to me under **gssoc-ext**, **hacktober-fest**

**Pull request merged**
