### PR TITLE
Update Tailwind Config for Responsive Design

### LINKED ISSUE #455: [style]: Responsive Header and Toggle Button Adjustment for Tablet View
### What's the style idea?

This update aims to enhance the user interface of the "DevDisplay" platform on tablet devices. Adjustments focus on aligning the header elements and optimizing the light/dark mode toggle button for screens with a max-width of 768px. These changes ensure that the header is clean, centered, and free of overflow issues while the toggle button remains accessible without crowding, providing a seamless experience for tablet users.

### Add screenshots

Add screenshots
Screenshot 2024-10-27 151538

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by shivhere007**
## Description

This update enhances the user interface of the "DevDisplay" platform on tablet devices by aligning header elements and optimizing the light/dark mode toggle button for screens with a max-width of 768px and 1024px. These adjustments ensure a clean, centered header and an accessible toggle button, providing a seamless experience for tablet users.

## Related Issues

Fixes #455 

## Changes Proposed

Custom Breakpoints Added: The md (medium) breakpoint has been set to 925px, allowing for a more tailored responsive design for medium-sized screens. The lg (large) breakpoint has been adjusted to 1100px, providing a better fit for larger screens while ensuring optimal layout and spacing. Other breakpoints remain unchanged at 640px for sm (small) and 1280px for xl (extra-large).

## Checklist

- [X] I have read and followed the [Contribution Guidelines](https://github.com/codeaashu/DevDisplay/blob/master/CONTRIBUTING.md).
- [X] All new and existing tests passed.
- [X] I have updated the documentation to reflect the changes I've made.
- [X] My code follows the code style of this project.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
After : 

Screenshot 2024-10-28 121107
Screenshot 2024-10-28 121139

Before : 

Screenshot 2024-10-28 122108
Screenshot 2024-10-28 122132

Kindly review this and merge it @codeaashu , @ishap11 , @madhukalita .

### CODE REVIEW

**Comment by codeaashu** [comment]
Hi @shivhere007  , thanks for your interest in contributing to DevDisplay!

Before we proceed, we noticed you haven't adding our profile on #DevDisplay also forgot to star the repo. It's like making an amazing sandwich and forgetting to take a bite! -- I think our repo's feeling a little lonely without your 🤗 So, be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻

**Comment by shivhere007** [comment]
Kindly check and merge at your earliest convenience @codeaashu , @ishap11 , @madhukalita .

**Comment by shivhere007** [comment]
I have already starred the project and just now added my profile too. Kindly review and merge my PR @codeaashu , @ishap11

**Comment by shivhere007** [comment]
Please check and merge my PR too @ishap11

**Comment by shivhere007** [comment]
@codeaashu kindly review and take some actions.

**Pull request closed without merging**
