### PR TITLE
add: Rohitha Aiswarya Dora Hanumanthu

### PR DESCRIPTION
**Pull request by RohithaAiswarya16**
## Checklist

- [x] I have read and followed the [Contribution Guidelines](https://github.com/codeaashu/DevDisplay/blob/master/CONTRIBUTING.md).
- [x] All new and existing tests passed.
- [x] I have updated the documentation to reflect the changes I've made.
- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by codeaashu** [comment]
Hi @RohithaAiswarya16 , thanks for your interest in contributing to DevDisplay!

We noticed you adding your profile on #DevDisplay but forgot to star the repo. It's like making an amazing sandwich and forgetting to take a bite! -- I think our repo's feeling a little lonely without your 🤗 So, be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

Thanks 👍🏻

**Comment by RohithaAiswarya16** [comment]
Yes, I have now starred the repo, sorry for that earlier. Please review and approve.

**Comment by madhukalita** [comment]
hey @RohithaAiswarya16 after some time check out your Linkedin & Twitter you will received a welcome post by DevDisplay Community

**Comment by RohithaAiswarya16** [comment]
Thank you.

**Pull request merged**
