### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Dipanita45**
## Description

<--Added security --->

#512 

## Checklist

- [yes] I have read and followed the [Contribution Guidelines](https://github.com/codeaashu/DevDisplay/blob/master/CONTRIBUTING.md).
- [yes] All new and existing tests passed.
- [yes] I have updated the documentation to reflect the changes I've made.
- [ yes] My code follows the code style of this project.
- [ yes] The title of my pull request is a short description of the requested changes.

Please merge my pull request and label me
@codeaashu

### CODE REVIEW

**Comment by madhukalita** [comment]
Great Work @Dipanita45 , thanks for your interest in contributing to DevDisplay!

Before we proceed, we noticed you haven't adding your profile on #DevDisplay also forgot to star the repo. It's like making an amazing sandwich and forgetting to take a bite! -- I think our repo's feeling a little lonely without your 🤗 So, be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻

**Comment by Dipanita45** [comment]
Please merge my pull request and label me 
@codeaashu

**Comment by Dipanita45** [comment]
My profile. @Dipanita45 
 Thank you for the chance 
Please merge my pull request and label me 
@codeaashu

**Comment by Dipanita45** [comment]
Please review and merge my pull request and label me 
@madhukalita  @codeaashu

**Pull request merged**
