### PR TITLE
Improved Slidebar - added star 🌟 Repo button and reduced text size

### PR DESCRIPTION
**Pull request by NishantRana07**
Improved Slidebar - added star 🌟 Repo button and reduced text size for better alignment of dark mode button

Screenshot 2024-10-17 003754
Screenshot 2024-10-17 003733

please merge this PR under GSSOC extd and Hacktoberfest

### CODE REVIEW

**Comment by codeaashu** [comment]
It's great but before that add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

**Comment by NishantRana07** [comment]
okay Sir 👍
i will add

**Comment by NishantRana07** [comment]
@codeaashu Profile also added 👍
please merge it with necessary labels

**Comment by codeaashu** [comment]
and if you good at Frontend , backend, or any technology 
join the DevDisplay whatsapp Community - https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4

**Comment by NishantRana07** [comment]
Can you merge this ?

**Comment by NishantRana07** [comment]
@codeaashu Bro any changes ?? i have also added my profile please merge it with required labels

**Comment by codeaashu** [comment]
Hi @NishantRana07, thanks for your interest in contributing to DevDisplay!

Before we proceed, we noticed you adding your profile on #DevDisplay but forgot to star the repo. It's like making an amazing sandwich and forgetting to take a bite! -- I think our repo's feeling a little lonely without your 🤗 

So, be sure to star the DevDisplay GitHub Repository. 🌟

💌 This is a mandatory step for all contributors. & It's is the first priority of contribution in DevDisplay 💌

🚀 We look forward to your contribution once these steps are completed. 🚀

Thanks 👍🏻

**Comment by NishantRana07** [comment]
@codeaashu already starred

**Comment by NishantRana07** [comment]
@codeaashu bro please merge this PR or close this

**Comment by madhukalita** [comment]
join the DevDisplay whatsapp Community - https://chat.whatsapp.com/Dcl21sgGDIpHURESSuH0p4

we need to talk regarding this

**Pull request merged**
