### PR TITLE
 add: jyothimanoj12  * added a new feature - tech resources page *

### PR DESCRIPTION
**Pull request by jyothimanoj12**
-  ********** FIXED ISSUE #109   *************

developed a Tech Resources page featuring a hero section with a dynamic background animation. This page includes sections for programming language courses, top GitHub repositories, and categorized AI tools, enhancing accessibility for tech enthusiasts. A footer provides links to external resources and social media. All components are reusable and responsive, ensuring a seamless user experience across devices. Additionally, animations enhance interactions, making the page visually appealing and engaging. This setup not only serves as a valuable resource hub for developers but also adheres to modern web development standards.****

** plz add gsoc extended , hacktober-accepted and also i think this issue could be a level 3 instead of level 2 , plz add them**

### CODE REVIEW

**Comment by codeaashu** [comment]
your code have error that's why it's failed in deployment in production
check ou the error & this on your local host if it working then send a pull request

so, let's Start working on this
but before that add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

Screenshot (1362)

**Comment by jyothimanoj12** [comment]
Ok i will

**Comment by jyothimanoj12** [comment]
I added my profile , but its showing deployment failed

**Comment by codeaashu** [comment]
please don't send too many files of pr in on time.

First send the PR for profile add in DevDisplay when it's accepted. then send another PR request

**Comment by codeaashu** [comment]
First add your profile on DevDisplay
It's is the first priority of contribution in DevDisplay

if you don't assign in this you will not be able to contribute on this project

**Comment by jyothimanoj12** [comment]
> First add your profile on DevDisplay
> 
> It's is the first priority of contribution in DevDisplay
> 
> 
> 
> if you don't assign in this you will not be able to contribute on this project

Ok first i need to add my profile right , after only i need to add the rest of the files right ??

**Pull request closed without merging**
